//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValaisBookingApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BookedRoom
    {
        [Key]
        public int IdBookedRoom { get; set; }
        public string IdBooking { get; set; }
        public string IdRoom { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Booking Booking { get; set; }
    }
}
